[package]
name = "binaryen-sys"
version = "0.1.0"
edition = "2021"
links = "binaryen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = ">= 0.2.126"

[build-dependencies]
cmake = "0.1.48"
bindgen = "0.60.1"